### ISSUE TITLE
add "conferences" widget

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cac-advanced-profiles#90]
Moved from mlaa/cbox-mla#183. @terrainsvagues says: 

>Desired functionality: A user can add an upcoming conference he/she will be attending to his/her portfolio (in a dedicated field for upcoming conferences). The conference title would be clickable; clicking on it would result in a list of other users attending that conference (see current behavior in 'Academic Interests'.)

Also related to mlaa/cbox-mla#184. 

Could use typeahead behavior here to standardize conferences.

**Comment by chriszarate** [comment]
Added in free form, for now.
