### ISSUE TITLE
Investigate ways to normalize taxonomy of academic interests

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cac-advanced-profiles#91]
Moved from mlaa/cbox-mla#184. 

@terrainsvagues says: 

>Desired functionality: when a user starts to fill in a portfolio field, (e.g. an academic interest), we provide autocomplete suggestions based on interests entered by other users.

>Use case: allows users to find others with similar interests or at the same institution by reducing the possibilities for confusion (19th vs. nineteenth vs Nineteenth vs 19; literature vs. lit, etc.)

>We should continue allow users to disregard autocomplete suggestions and fill in their own data.

**Comment by terrainsvagues** [comment]
Another vote from this by attendees at Commons workshop in Amherst. They claim to be interested in many things, but they don't always remember those things. Typeahead or (better?) a drop down would be enormously helpful in this case.

**Comment by JonathanReeve** [comment]
I think the first step here will be: find and import a canonical, manageable list of possible interests. Just a text file containing items such as: 
 * 19th Century British Literature
 * 18th Century British Literature

and then I can work on a kind of database of aliases that maps "19th" to "Nineteenth," and so on. 
I could do this, but also any help here (from those that might know their way around the Bibliography, especially) would speed things up a lot. Alternatively, if there's anyone in Bibliography that already has a list like this, that could be very useful.

**Comment by terrainsvagues** [comment]
I checked with Barbara at the bibliography and she says that they have "literally thousands" of subjects—and no way of parsing those used most often from those neglected.

**Comment by JonathanReeve** [comment]
I tried looking through Library of Congress subject headings, and I realized that a) there are also way too many there, even among those with a high level in the hierarchy, and b) as a non-librarian, I have no idea how to negotiate those lists. 

Here are some more ideas: 

 * we use some sort of reference book, like Abrams's _Glossary of Literary Terms_, removing entries that don't seem like they could be interests. 
 * we start a thread on the Commons explaining this problem and asking for suggestions of how to handle it. 
 * we skip creation of a list, and just autosuggest any interest with more than a certain threshold of members with that interest. This would mean that we could have "19th century" and "eighteenth century" as interests.

**Comment by rekmla** [comment]
Here is a somewhat limited list from AcademicCommons that might serve as a starting point to seed an autosuggest funtion:

"African history", 
"American history", 
"Ancient history", 
"Asian history", 
"Black history", 
"Canadian history", 
"European history", 
"History", 
"History of Oceania", 
"History of science", 
"Latin American history", 
"Medieval history", 
"Middle Eastern history", 
"Military history", 
"Modern history", 
"Russian history", 
"World history", 
"African literature", 
"American literature", 
"Ancient languages", 
"Asian literature", 
"British and Irish literature", 
"Canadian literature", 
"Caribbean literature", 
"Classical literature", 
"Comparative literature", 
"English literature", 
"French Canadian literature", 
"Germanic literature", 
"Icelandic & Scandinavian literature", 
"Language", 
"Latin American literature", 
"Linguistics", 
"Literature", 
"Literature of Oceania", 
"Medieval literature", 
"Middle Eastern literature", 
"Modern language", 
"Modern literature", 
"Rhetoric", 
"Romance literature", 
"Slavic literature", 
"Aesthetics", 
"Biblical studies", 
"Canon law", 
"Clerical studies", 
"Comparative religion", 
"Divinity", 
"Epistemology", 
"Ethics", 
"Logic", 
"Metaphysics", 
"Pastoral counseling", 
"Philosophy", 
"Philosophy of Religion", 
"Philosophy of science", 
"Religion", 
"Religious history", 
"Spirituality", 
"Theology"
